[project]
name = "fastapi-send-email"
version = "0.1.0"
description = "microservice for sending emails at the request of the main application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "fastapi-mail>=1.4.2",
    "pytest>=8.3.4",
    "uvicorn>=0.34.0",
]
